name: CI - Integration and e2e Tests

on: [pull_request]

jobs:
  run-int-e2e-tests:
    name: Run Integration and e2e Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: projectdb

    # definir passos necessários para baixar o app e rodar os testes

    steps:
      - uses: actions/checkout@v6 # baixar codigo do app no ubuntu

      - uses: actions/setup-node@v6 # configurar o node
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci # instalar dependencia sem interação

      - run: npx prisma generate --schema ./src/shared/infrastructure/database/prisma/schema.prisma
        env:
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'

      - run: npm run test:int
        env:
          PORT: 3001
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'

      - run: npm run test:e2e
        env:
          PORT: 3001
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/projectdb?schema=public'
